server:
  name: "Go E-commerce API Server"
  port: 8080
  host: "localhost"
  rate_limit:
    enabled: true
    rate_limit: 5
    rate_limit_window: 1m

token:
  access_key: "ZHqr1DAN5utpnzH/m3yso6MfZ7jv3g18IXfdfwnM2+s="
  access_duration: 168h    # 7 days
  refresh_key: "GFTR4lalgqPCUKpkuAKC7VUwE6yM0d4Yqe3Fg3hRn9I="
  refresh_duration: 720h   # 30 days


redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

mongodb:
  uri: "mongodb://localhost:27017"
  database: "ecommerce"
  timeout: 10s

email:
  sender_name: Riadul Islam
  sender_address: dev.riadul@gmail.com
  sender_password: rpxr locs kcbv bkdz
  exp_duration: 5m