@baseUrl = http://localhost:8080/api/v1

### Register User
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Md Riadul Islam",
  "email": "dev.riadul1@gmail.com",
  "password": "dev.Riad2654",
  "phone": "+8801764707804"
}